Загрузите созданный вами в предыдущем упражнении JSON-файл в DataFrame.

Установите CarNumberстолбец в качестве индекса.

In [1]:
import pandas as pd

Загрузите созданный вами в предыдущем упражнении JSON-файл в DataFrame.

Установите CarNumberстолбец в качестве индекса.

In [2]:
df = pd.read_json('../ex02/auto.json')
df.set_index('CarNumber', inplace=True)
df

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
E432XX77RUS        1   6500.000000  Toyota    Camry
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   8594.586466  Toyota  Corolla

[725 rows x 4 columns]

2. Выберите следующие варианты:

Отобразить строки, где сумма штрафов превышает 2100.
Отобразите строки, где сумма штрафов превышает 2100, а сумма возврата равна 2.
Отобразить строки, в которых модели взяты из списка: [’Focus’, ’Corolla’].
Отобразить строки, в которых номер автомобиля взят из списка: [’Y7689C197RUS’, ’92928M178RUS’, ’7788KT197RUS’, ’H115YO163RUS’, ’X758HY197RUS’].

In [17]:
df[df['Fines']>2100]

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
E432XX77RUS        1   6500.000000      Toyota    Camry
92918M178RUS       1   5700.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
E40577152RUS       1   8594.586466        Ford    Focus
...              ...           ...         ...      ...
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
O22097197RUS       1  24300.000000        Ford    Focus
M0309X197RUS       1  22300.000000        Ford    Focus
H419XE197RUS       2   8594.586466      Toyota  Corolla

[455 rows x 4 columns]

In [18]:
df[(df['Fines']>2100) & (df['Refund']==2)]

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
707987163RUS       2   2200.000000        Ford    Focus
K330T8197RUS       2   8200.000000       Skoda  Octavia
M592CH197RUS       2   8594.586466       Skoda  Octavia
...              ...           ...         ...      ...
O136HO197RUS       2   7800.000000      Toyota  Corolla
O68897197RUS       2  12300.000000        Ford    Focus
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
H419XE197RUS       2   8594.586466      Toyota  Corolla

[309 rows x 4 columns]

In [19]:
df[df.Model.isin(['Focus', 'Corolla'])]

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
H234YH197RUS       2   6000.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   8594.586466  Toyota  Corolla

[593 rows x 4 columns]

In [20]:
numbers = ['Y7689C197RUS', '92928M178RUS', '7788KT197RUS', 'H115YO163RUS', 'X758HY197RUS']
df[df.index.isin(numbers)]

              Refund          Fines  Make  Model
CarNumber
92928M178RUS       1    8594.586466  Ford  Focus
H115YO163RUS       1    2200.000000  Ford  Focus
7788KT197RUS       2   12000.000000  Ford  Focus
X758HY197RUS       2   24200.000000  Ford  Focus
X758HY197RUS       2   72600.000000  Ford  Focus
Y7689C197RUS       1   27000.000000  Ford  Focus
92928M178RUS       1     600.000000  Ford  Focus
H115YO163RUS       1    8594.586466  Ford  Focus
H115YO163RUS       2    1100.000000  Ford  Focus
7788KT197RUS       2    8594.586466  Ford  Focus
7788KT197RUS       1   20000.000000  Ford  Focus
X758HY197RUS       2  145200.000000  Ford  Focus
92928M178RUS       1    1200.000000  Ford  Focus
Y7689C197RUS       2    9000.000000  Ford  Focus
Y7689C197RUS       2   45000.000000  Ford  Focus
7788KT197RUS       2    4000.000000  Ford  Focus
Y7689C197RUS       1   36000.000000  Ford  Focus
92928M178RUS       2    3000.000000  Ford  Focus

Выполните агрегирование с помощью операторов ` makeand` model.

Отобразить медианные значения штрафов, сгруппированные по make.
Отобразить медианные значения штрафов, сгруппированные по параметрам makeи model.
Чтобы понять, можно ли доверять медианным значениям, отобразите количество штрафов, сгруппированных по категориям make.model
makeДля modelлучшего понимания различий отобразите минимальные и максимальные штрафы, сгруппированные по категориям .
makeДля modelлучшего понимания дисперсии отобразите стандартное отклонение штрафов, сгруппированных по категориям .

In [21]:
df.groupby(by=['Make']).median()['Fines']

/Users/dinarvaliev/ds_21/DSB7_Pandas.ID_1577650-1/.venv/lib/python3.13/site-packages/numpy/lib/_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/dinarvaliev/ds_21/DSB7_Pandas.ID_1577650-1/.venv/lib/python3.13/site-packages/numpy/lib/_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

TypeError: agg function failed [how->median,dtype->object]

In [22]:
df.groupby(by=['Make','Model']).median()['Fines']

Make        Model
Ford        Focus      3500.0
            Mondeo     7650.0
Skoda       Octavia    3250.0
Toyota      Camry      7700.0
            Corolla    7700.0
Volkswagen  Golf       4800.0
            Jetta      2800.0
            Passat     3500.0
            Touareg    5800.0
Name: Fines, dtype: float64

In [23]:
df.groupby(by=['Make','Model']).count()['Fines']

Make        Model
Ford        Focus      575
            Mondeo       6
Skoda       Octavia     48
Toyota      Camry       16
            Corolla     18
Volkswagen  Golf        20
            Jetta        6
            Passat      22
            Touareg      5
Name: Fines, dtype: int64

In [24]:
df.groupby(by=['Make','Model']).min()['Fines']

Make        Model
Ford        Focus       100.0
            Mondeo     1100.0
Skoda       Octavia     300.0
Toyota      Camry       500.0
            Corolla     900.0
Volkswagen  Golf        200.0
            Jetta       500.0
            Passat      100.0
            Touareg     500.0
Name: Fines, dtype: float64

In [25]:
df.groupby(['Make','Model']).max()['Fines']

Make        Model
Ford        Focus      180000.000000
            Mondeo      46200.000000
Skoda       Octavia    145000.000000
Toyota      Camry       22400.000000
            Corolla     34300.000000
Volkswagen  Golf       168000.000000
            Jetta       46000.000000
            Passat      29700.000000
            Touareg      8594.586466
Name: Fines, dtype: float64

In [26]:
df.groupby(['Make', 'Model']).std()['Fines']

Make        Model
Ford        Focus      15041.269437
            Mondeo     18987.329108
Skoda       Octavia    24339.742174
Toyota      Camry       6410.250654
            Corolla     9629.325617
Volkswagen  Golf       36950.839950
            Jetta      17743.026799
            Passat      6969.739135
            Touareg     3461.778173
Name: Fines, dtype: float64

In [ ]:
4. Создавайте агрегированные данные по номерам автомобилей.

Отобразите номера автомобилей, сгруппированные по количеству штрафов в порядке убывания. Мы хотим найти тех, кто чаще всего нарушал закон.
Выберите из исходного датафрейма все строки, соответствующие номеру автомобиля, занимающего первое место. Мы хотим немного приблизиться к изображению.
Отобразите номера автомобилей, сгруппированные по сумме штрафов в порядке убывания. Нам нужно найти тех, кто заплатил больше всего.
Выберите все строки, соответствующие номеру автомобиля с самым высоким номером в исходном датафрейме. Мы хотим немного приблизить изображение.
Отобразите таблицу, которая отвечает на вопрос: «Существуют ли номера автомобилей, связанные с разными моделями?»

In [27]:
df.groupby(df.index)['Fines'].count().sort_values(ascending=False)

CarNumber
Y7689C197RUS    4
92928M178RUS    4
7788KT197RUS    4
H115YO163RUS    3
X758HY197RUS    3
               ..
E42577152RUS    1
E42377152RUS    1
E41977152RUS    1
E41577152RUS    1
H917TC36RUS     1
Name: Fines, Length: 531, dtype: int64

In [28]:
df[df.index.isin(['Y7689C197RUS', '92928M178RUS', '7788KT197RUS'])].sort_index()

              Refund         Fines  Make  Model
CarNumber
7788KT197RUS       2  12000.000000  Ford  Focus
7788KT197RUS       2   8594.586466  Ford  Focus
7788KT197RUS       1  20000.000000  Ford  Focus
7788KT197RUS       2   4000.000000  Ford  Focus
92928M178RUS       1   8594.586466  Ford  Focus
92928M178RUS       1    600.000000  Ford  Focus
92928M178RUS       1   1200.000000  Ford  Focus
92928M178RUS       2   3000.000000  Ford  Focus
Y7689C197RUS       1  27000.000000  Ford  Focus
Y7689C197RUS       2   9000.000000  Ford  Focus
Y7689C197RUS       2  45000.000000  Ford  Focus
Y7689C197RUS       1  36000.000000  Ford  Focus

In [29]:
# Отобразите номера автомобилей, сгруппированные по сумме штрафов 
# в порядке убывания. Нам нужно найти тех, кто заплатил больше всего

df.groupby(df.index)['Fines'].sum().sort_values(ascending=False)

CarNumber
X758HY197RUS    242000.0
9020YC197RUS    217500.0
M0279X197RUS    216000.0
Y352O8197RUS    207200.0
Y778EE197RUS    192000.0
                  ...
83218C154RUS       100.0
Y195O8161RUS       100.0
K376HE161RUS       100.0
705787163RUS       100.0
K326T8197RUS       100.0
Name: Fines, Length: 531, dtype: float64

In [30]:
df[df.index.isin(['X758HY197RUS'])]

              Refund     Fines  Make  Model
CarNumber
X758HY197RUS       2   24200.0  Ford  Focus
X758HY197RUS       2   72600.0  Ford  Focus
X758HY197RUS       2  145200.0  Ford  Focus

In [31]:
df.groupby('CarNumber').count()['Model'].sort_values(ascending=False)

CarNumber
7788KT197RUS    4
Y7689C197RUS    4
92928M178RUS    4
7361C8197RUS    3
X758HY197RUS    3
               ..
X023HY197RUS    0
M5039X197RUS    0
96907X197RUS    0
Y693HM197RUS    0
Y687HM197RUS    0
Name: Model, Length: 531, dtype: int64

<class 'pandas.core.frame.DataFrame'>
Index: 725 entries, Y163O8161RUS to H419XE197RUS
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Refund  725 non-null    int64
 1   Fines   725 non-null    float64
 2   Make    725 non-null    object
 3   Model   716 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 44.5+ KB