1. Прочитайте JSON-файл, который вы сохранили в ex02.

Один из столбцов содержит числа с плавающей запятой, поэтому давайте определим его формат в Pandas, используя pd.options.display.float_format`:`. Числа с плавающей запятой должны отображаться с двумя знаками после запятой.
В модели отсутствуют некоторые значения; ничего с ними делать не следует.

In [26]:
import pandas as pd
import numpy as np

1.Прочитайте JSON-файл, который вы сохранили в ex02.

Один из столбцов содержит числа с плавающей запятой, поэтому давайте определим его формат в Pandas, используя pd.options.display.float_format`:`. Числа с плавающей запятой должны отображаться с двумя знаками после запятой.
В модели отсутствуют некоторые значения; ничего с ними делать не следует.

In [27]:
df = pd.read_json('../ex02/auto.json')
pd.options.display.float_format = '{:,.2f}'.format
df

        CarNumber  Refund     Fines    Make    Model
0    Y163O8161RUS       2  3,200.00    Ford    Focus
1     E432XX77RUS       1  6,500.00  Toyota    Camry
2     7184TT36RUS       1  2,100.00    Ford    Focus
3    X582HE161RUS       2  2,000.00    Ford    Focus
4    92918M178RUS       1  5,700.00    Ford    Focus
..            ...     ...       ...     ...      ...
720  Y163O8161RUS       2  1,600.00    Ford    Focus
721  M0309X197RUS       1 22,300.00    Ford    Focus
722  O673E8197RUS       2    600.00    Ford    Focus
723  8610T8154RUS       1  2,000.00    Ford    Focus
724  H419XE197RUS       2  8,594.59  Toyota  Corolla

[725 rows x 5 columns]

2. Обогатите фрейм данных, используя выборку из этого фрейма данных.

Создайте выборку из 200 новых наблюдений, используя random_state = 21.

Выборка не должна содержать новых комбинаций car number, make, и model, поэтому весь набор данных будет согласован в этом отношении.
refundНа столбцы и нет никаких ограничений fines. Вы можете случайным образом выбрать значение из этих столбцов и применить его к любому номеру автомобиля.


Объедините образец с исходным фреймом данных, чтобы создать новый фрейм данных concat_rows.

In [ ]:
sample = df.sample(n = 200, random_state=21).reset_index(drop=True)
sample

        CarNumber  Refund     Fines        Make   Model
0    M0299X197RUS       2 19,200.00        Ford   Focus
1    83298C154RUS       2  8,594.59        Ford   Focus
2    H957HY161RUS       1  2,000.00        Ford   Focus
3     T941CC96RUS       1  2,000.00        Ford   Focus
4    H966HY161RUS       1    500.00        Ford   Focus
..            ...     ...       ...         ...     ...
195  8182XX154RUS       1    200.00        Ford   Focus
196   X796TH96RUS       1    500.00        Ford   Focus
197  T011MY163RUS       2  4,000.00        Ford   Focus
198   T341CC96RUS       2  1,000.00  Volkswagen  Passat
199   T119CT96RUS       1  2,000.00        Ford   Focus

[200 rows x 5 columns]

In [29]:
sample_for_Refund = df.sample(n = 200, random_state=42).reset_index(drop=True)
sample_for_Refund['Refund']

0      1
1      2
2      2
3      1
4      1
      ..
195    1
196    1
197    2
198    2
199    2
Name: Refund, Length: 200, dtype: int64

In [30]:
sample_for_Fines = df.sample(n = 200, random_state=41).reset_index(drop=True)
sample_for_Fines['Fines']

0     2,600.00
1     2,000.00
2       500.00
3     7,800.00
4     1,400.00
        ...
195     500.00
196     500.00
197   1,000.00
198   1,500.00
199   2,200.00
Name: Fines, Length: 200, dtype: float64

In [31]:
sample['Fines'] = sample_for_Fines['Fines']
sample['Refund'] = sample_for_Refund['Refund']
sample

        CarNumber  Refund    Fines        Make   Model
0    M0299X197RUS       1 2,600.00        Ford   Focus
1    83298C154RUS       2 2,000.00        Ford   Focus
2    H957HY161RUS       2   500.00        Ford   Focus
3     T941CC96RUS       1 7,800.00        Ford   Focus
4    H966HY161RUS       1 1,400.00        Ford   Focus
..            ...     ...      ...         ...     ...
195  8182XX154RUS       1   500.00        Ford   Focus
196   X796TH96RUS       1   500.00        Ford   Focus
197  T011MY163RUS       2 1,000.00        Ford   Focus
198   T341CC96RUS       2 1,500.00  Volkswagen  Passat
199   T119CT96RUS       2 2,200.00        Ford   Focus

[200 rows x 5 columns]

In [ ]:
concat_rows =  pd.concat([df, sample])
concat_rows

        CarNumber  Refund    Fines        Make   Model
0    Y163O8161RUS       2 3,200.00        Ford   Focus
1     E432XX77RUS       1 6,500.00      Toyota   Camry
2     7184TT36RUS       1 2,100.00        Ford   Focus
3    X582HE161RUS       2 2,000.00        Ford   Focus
4    92918M178RUS       1 5,700.00        Ford   Focus
..            ...     ...      ...         ...     ...
195  8182XX154RUS       1   500.00        Ford   Focus
196   X796TH96RUS       1   500.00        Ford   Focus
197  T011MY163RUS       2 1,000.00        Ford   Focus
198   T341CC96RUS       2 1,500.00  Volkswagen  Passat
199   T119CT96RUS       2 2,200.00        Ford   Focus

[925 rows x 5 columns]

In [33]:
concat_rows.count()

CarNumber    925
Refund       925
Fines        925
Make         925
Model        914
dtype: int64

In [34]:
np.random.seed(21)

In [35]:
Year = pd.Series([np.random.randint(1980, 2019) for i in range(len(concat_rows))])
Year

0      1989
1      1995
2      1984
3      2015
4      2014
       ...
920    1996
921    2002
922    1996
923    2012
924    1984
Length: 925, dtype: int64

In [36]:
concat_rows['Year'] = Year.astype('int')
fines = concat_rows
fines

        CarNumber  Refund    Fines        Make   Model  Year
0    Y163O8161RUS       2 3,200.00        Ford   Focus  1989
1     E432XX77RUS       1 6,500.00      Toyota   Camry  1995
2     7184TT36RUS       1 2,100.00        Ford   Focus  1984
3    X582HE161RUS       2 2,000.00        Ford   Focus  2015
4    92918M178RUS       1 5,700.00        Ford   Focus  2014
..            ...     ...      ...         ...     ...   ...
195  8182XX154RUS       1   500.00        Ford   Focus  2012
196   X796TH96RUS       1   500.00        Ford   Focus  1998
197  T011MY163RUS       2 1,000.00        Ford   Focus  1983
198   T341CC96RUS       2 1,500.00  Volkswagen  Passat  1983
199   T119CT96RUS       2 2,200.00        Ford   Focus  1989

[925 rows x 6 columns]

In [37]:
fines.count()

CarNumber    925
Refund       925
Fines        925
Make         925
Model        914
Year         925
dtype: int64

5. Обогатите фрейм данных данными из другого фрейма данных.

Создайте новый датафрейм, содержащий номера автомобилей и их владельцев.

Получите список самых популярных фамилий в США (файл surname.json находится в папке datasets).
Создайте новую серию с фамилиями. Она не должна содержать специальных символов, таких как запятые или скобки. Количество должно равняться числу уникальных номеров автомобилей в выборке (используйте random_state = 21).
Создайте датафрейм ownersс двумя столбцами: CarNumberи SURNAME.


Добавьте в таблицу данных еще пять наблюдений fines. Придумайте свои собственные идеи для CarNumber, и т. д.
Удалите последние 20 наблюдений из ownersдатафрейма и добавьте три новых наблюдения, которые не совпадают с теми, что были добавлены в finesдатафрейм.
Объедините два датафрейма.

Новый датафрейм должен содержать только те номера автомобилей, которые присутствуют в обоих датафреймах.
Новый датафрейм должен содержать все номера автомобилей из обоих датафреймов.
Новый датафрейм должен содержать только номера автомобилей из finesисходного датафрейма.
Новый датафрейм должен содержать только номера автомобилей из ownersисходного датафрейма.

In [38]:
surname = pd.read_json("../data/surname.json")
surname = surname.iloc[1:]
surname = surname.set_axis(['NAME', 'COUNT', 'RANK'], axis=1)
surname

         NAME    COUNT RANK
1       ADAMS   427865   42
2       ALLEN   482607   33
3     ALVAREZ   233983   92
4    ANDERSON   784404   15
5      BAILEY   277845   72
..        ...      ...  ...
96   WILLIAMS  1625252    3
97     WILSON   801882   14
98       WOOD   250715   84
99     WRIGHT   458980   35
100     YOUNG   484447   32

[100 rows x 3 columns]

In [39]:
onwer_car = concat_rows.drop_duplicates('CarNumber')['CarNumber']
onwer_car = onwer_car.reset_index(drop=True)
onwer_car

0      Y163O8161RUS
1       E432XX77RUS
2       7184TT36RUS
3      X582HE161RUS
4      92918M178RUS
           ...
526    O136HO197RUS
527    O22097197RUS
528    M0309X197RUS
529    O673E8197RUS
530    8610T8154RUS
Name: CarNumber, Length: 531, dtype: object

In [40]:
owner_name = surname['NAME'].sample(n=531, random_state=21, replace=True, ignore_index=True)
owner_name

0      RICHARDSON
1            ROSS
2          MORGAN
3          BAILEY
4           LOPEZ
          ...
526      CAMPBELL
527          HALL
528         BAKER
529          DIAZ
530        MORGAN
Name: NAME, Length: 531, dtype: object

In [41]:
owners = pd.DataFrame(data = onwer_car)
owners['SURNAME'] = owner_name
owners

        CarNumber     SURNAME
0    Y163O8161RUS  RICHARDSON
1     E432XX77RUS        ROSS
2     7184TT36RUS      MORGAN
3    X582HE161RUS      BAILEY
4    92918M178RUS       LOPEZ
..            ...         ...
526  O136HO197RUS    CAMPBELL
527  O22097197RUS        HALL
528  M0309X197RUS       BAKER
529  O673E8197RUS        DIAZ
530  8610T8154RUS      MORGAN

[531 rows x 2 columns]

In [42]:
data01 = pd.Series(['01','02', '03', '04', '05'], name='CarNumber')
data02 = pd.Series([np.random.choice(fines['Refund']) for i in range(5)], name='Refund')
data03 = pd.Series([np.random.choice(fines['Fines']) for i in range(5)], name='Fines')
data04 = pd.Series([np.random.choice(fines['Make']) for i in range(5)], name='Make')
data05 = pd.Series([np.random.choice(fines['Model']) for i in range(5)], name='Model')
data06 = pd.Series([np.random.choice(fines['Year']) for i in range(5)], name='Year')

df_s = pd.DataFrame([data01, data02, data03, data04, data05, data06])
df_s = df_s.T
fines = pd.concat([fines, df_s])
fines

       CarNumber Refund     Fines    Make  Model  Year
0   Y163O8161RUS      2  3,200.00    Ford  Focus  1989
1    E432XX77RUS      1  6,500.00  Toyota  Camry  1995
2    7184TT36RUS      1  2,100.00    Ford  Focus  1984
3   X582HE161RUS      2  2,000.00    Ford  Focus  2015
4   92918M178RUS      1  5,700.00    Ford  Focus  2014
..           ...    ...       ...     ...    ...   ...
0             01      1  5,800.00  Toyota  Focus  2017
1             02      1 41,700.00    Ford  Focus  2008
2             03      1    200.00    Ford  Focus  1985
3             04      2    800.00    Ford  Focus  2000
4             05      1  6,200.00    Ford  Focus  1987

[930 rows x 6 columns]

In [43]:
owners_test = owners.drop(owners.tail(20).index)
data07 = pd.Series(['6666666666','77777777777', '888888888888'], name='CarNumber')
data08 = pd.Series([np.random.choice(owners['SURNAME']) for i in range(3)], name='SURNAME')
add_3 = pd.DataFrame([data07, data08])
owners = pd.concat([owners, add_3.T])

In [44]:
test1 = pd.merge(fines, owners_test, on='CarNumber', how='inner')
test1

        CarNumber Refund    Fines        Make   Model  Year     SURNAME
0    Y163O8161RUS      2 3,200.00        Ford   Focus  1989  RICHARDSON
1     E432XX77RUS      1 6,500.00      Toyota   Camry  1995        ROSS
2     7184TT36RUS      1 2,100.00        Ford   Focus  1984      MORGAN
3    X582HE161RUS      2 2,000.00        Ford   Focus  2015      BAILEY
4    92918M178RUS      1 5,700.00        Ford   Focus  2014       LOPEZ
..            ...    ...      ...         ...     ...   ...         ...
894  8182XX154RUS      1   500.00        Ford   Focus  2012       SMITH
895   X796TH96RUS      1   500.00        Ford   Focus  1998      WATSON
896  T011MY163RUS      2 1,000.00        Ford   Focus  1983     SANDERS
897   T341CC96RUS      2 1,500.00  Volkswagen  Passat  1983       PEREZ
898   T119CT96RUS      2 2,200.00        Ford   Focus  1989        RUIZ

[899 rows x 7 columns]

In [45]:
test2 = pd.merge(fines, owners_test, on='CarNumber', how='outer')
test2

        CarNumber Refund     Fines    Make  Model  Year SURNAME
0              01      1  5,800.00  Toyota  Focus  2017     NaN
1              02      1 41,700.00    Ford  Focus  2008     NaN
2              03      1    200.00    Ford  Focus  1985     NaN
3              04      2    800.00    Ford  Focus  2000     NaN
4              05      1  6,200.00    Ford  Focus  1987     NaN
..            ...    ...       ...     ...    ...   ...     ...
925  Y973O8197RUS      2  8,594.59    Ford  Focus  2005   YOUNG
926  Y973O8197RUS      1 34,800.00    Ford  Focus  2013   YOUNG
927  Y973O8197RUS      1 69,600.00    Ford  Focus  1989   YOUNG
928  Y973O8197RUS      2 17,000.00    Ford  Focus  1981   YOUNG
929  Y973O8197RUS      1  1,000.00    Ford  Focus  2004   YOUNG

[930 rows x 7 columns]

In [46]:
test3 = pd.merge(fines, owners_test, on='CarNumber', how='left')
test3

        CarNumber Refund     Fines    Make  Model  Year     SURNAME
0    Y163O8161RUS      2  3,200.00    Ford  Focus  1989  RICHARDSON
1     E432XX77RUS      1  6,500.00  Toyota  Camry  1995        ROSS
2     7184TT36RUS      1  2,100.00    Ford  Focus  1984      MORGAN
3    X582HE161RUS      2  2,000.00    Ford  Focus  2015      BAILEY
4    92918M178RUS      1  5,700.00    Ford  Focus  2014       LOPEZ
..            ...    ...       ...     ...    ...   ...         ...
925            01      1  5,800.00  Toyota  Focus  2017         NaN
926            02      1 41,700.00    Ford  Focus  2008         NaN
927            03      1    200.00    Ford  Focus  1985         NaN
928            04      2    800.00    Ford  Focus  2000         NaN
929            05      1  6,200.00    Ford  Focus  1987         NaN

[930 rows x 7 columns]

In [47]:
test4 = pd.merge(fines, owners_test, on='CarNumber', how='right')
test4

        CarNumber Refund     Fines    Make    Model  Year     SURNAME
0    Y163O8161RUS      2  3,200.00    Ford    Focus  1989  RICHARDSON
1    Y163O8161RUS      2  1,600.00    Ford    Focus  1999  RICHARDSON
2     E432XX77RUS      1  6,500.00  Toyota    Camry  1995        ROSS
3     E432XX77RUS      2 13,000.00  Toyota    Camry  1992        ROSS
4     7184TT36RUS      1  2,100.00    Ford    Focus  1984      MORGAN
..            ...    ...       ...     ...      ...   ...         ...
894  E41977152RUS      2  2,400.00    Ford    Focus  2001       BAKER
895  9464EX178RUS      2  2,100.00    Ford    Focus  1993      MARTIN
896  O50197197RUS      2  7,800.00    Ford    Focus  1986      WRIGHT
897  7608EE777RUS      1  4,000.00   Skoda  Octavia  2013        HILL
898  7608EE777RUS      1    100.00   Skoda  Octavia  2011        HILL

[899 rows x 7 columns]

In [48]:
pd.pivot_table(fines,
         columns='Year',
         values='Fines',
         index=['Make', 'Model'],
         aggfunc={'Fines': np.sum})

/var/folders/_d/q8_c5ntn1zsdjh_6zk89_ch40000gn/T/ipykernel_64779/3271954270.py:1: FutureWarning: The provided callable <function sum at 0x108d718a0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(fines,

Year                    1980       1981      1982       1983      1984  \
Make       Model
Ford       Focus   67,300.00 293,489.17 69,700.00 175,494.59 99,900.00
           Mondeo        NaN        NaN 46,200.00        NaN       NaN
Skoda      Octavia  8,594.59   1,900.00 29,494.59   9,794.59    300.00
Toyota     Camry   12,000.00        NaN       NaN        NaN  1,000.00
           Corolla       NaN   6,800.00       NaN  12,800.00  8,594.59
           Focus         NaN        NaN       NaN        NaN       NaN
Volkswagen Golf    23,400.00   8,594.59  5,000.00     200.00       NaN
           Jetta         NaN   1,000.00       NaN        NaN       NaN
           Passat     900.00  12,600.00       NaN   2,600.00  8,594.59
           Touareg       NaN        NaN       NaN        NaN       NaN

Year                     1985      1986      1987      1988       1989  ...  \
Make       Model                                                        ...
Ford       Focus   351,783.76 62,200.00 99,394.59 57,978.35 171,294.59  ...
           Mondeo         NaN       NaN       NaN       NaN        NaN  ...
Skoda      Octavia  54,794.59       NaN  2,000.00  5,100.00   8,594.59  ...
Toyota     Camry          NaN 37,200.00       NaN       NaN     800.00  ...
           Corolla        NaN       NaN 55,300.00       NaN   7,800.00  ...
           Focus          NaN       NaN       NaN       NaN        NaN  ...
Volkswagen Golf    168,000.00       NaN       NaN       NaN     300.00  ...
           Jetta     9,000.00       NaN       NaN 46,000.00        NaN  ...
           Passat         NaN 16,000.00  2,000.00  8,594.59        NaN  ...
           Touareg        NaN       NaN       NaN       NaN        NaN  ...

Year                     2009       2010       2011       2012       2013  \
Make       Model
Ford       Focus   152,994.59 179,700.00 134,394.59 242,689.17 250,789.17
           Mondeo         NaN        NaN        NaN        NaN  41,100.00
Skoda      Octavia        NaN   2,500.00   3,100.00   1,700.00  11,800.00
Toyota     Camry          NaN  22,400.00        NaN   7,500.00        NaN
           Corolla   8,594.59   6,000.00        NaN        NaN  45,000.00
           Focus          NaN        NaN        NaN        NaN        NaN
Volkswagen Golf           NaN        NaN        NaN        NaN        NaN
           Jetta          NaN        NaN        NaN        NaN  67,200.00
           Passat         NaN   9,500.00        NaN        NaN   1,600.00
           Touareg   5,800.00        NaN        NaN        NaN        NaN

Year                    2014       2015       2016      2017       2018
Make       Model
Ford       Focus   72,878.35 224,500.00 115,089.17 99,900.00  87,800.00
           Mondeo        NaN        NaN        NaN  8,600.00        NaN
Skoda      Octavia  6,200.00  16,394.59  48,000.00  2,400.00 153,200.00
Toyota     Camry         NaN        NaN        NaN       NaN        NaN
           Corolla       NaN        NaN        NaN       NaN        NaN
           Focus         NaN        NaN        NaN  5,800.00        NaN
Volkswagen Golf    33,400.00        NaN        NaN       NaN        NaN
           Jetta         NaN        NaN        NaN       NaN        NaN
           Passat  36,000.00        NaN        NaN       NaN        NaN
           Touareg       NaN        NaN        NaN       NaN        NaN

[10 rows x 39 columns]

In [49]:
fines.to_csv('../data/fines.csv', index=False)
owners.to_csv('../data/owners.csv', index=False)

In [50]:
fines

       CarNumber Refund     Fines    Make  Model  Year
0   Y163O8161RUS      2  3,200.00    Ford  Focus  1989
1    E432XX77RUS      1  6,500.00  Toyota  Camry  1995
2    7184TT36RUS      1  2,100.00    Ford  Focus  1984
3   X582HE161RUS      2  2,000.00    Ford  Focus  2015
4   92918M178RUS      1  5,700.00    Ford  Focus  2014
..           ...    ...       ...     ...    ...   ...
0             01      1  5,800.00  Toyota  Focus  2017
1             02      1 41,700.00    Ford  Focus  2008
2             03      1    200.00    Ford  Focus  1985
3             04      2    800.00    Ford  Focus  2000
4             05      1  6,200.00    Ford  Focus  1987

[930 rows x 6 columns]