In [1]:
import pandas as pd

In [3]:
col_names = ['datetime', 'user']
views = pd.read_csv('../data/feed-views.log', sep='\t', names = col_names)
views

                        datetime       user
0     2020-04-17 12:01:08.463179      artem
1     2020-04-17 12:01:23.743946      artem
2     2020-04-17 12:27:30.646665      artem
3     2020-04-17 12:35:44.884757      artem
4     2020-04-17 12:35:52.735016      artem
...                          ...        ...
1071  2020-05-21 18:45:20.441142  valentina
1072  2020-05-21 23:03:06.457819      maxim
1073  2020-05-21 23:23:49.995349      pavel
1074  2020-05-21 23:49:22.386789      artem
1075  2020-05-22 10:36:14.662600      artem

[1076 rows x 2 columns]

In [4]:
# Конвертировать datetimeв datetime64[ns] Dtype.
views['datetime'] = pd.to_datetime(views.datetime)
print(views['datetime'].dtype)

datetime64[ns]

In [5]:
# Извлечь год, месяц, день, час, минуту и ​​секунду из значений столбца datetimeв новые столбцы.

# Извлечение каждого компонента в отдельный столбец

views['year'] = views['datetime'].dt.year
views['month'] = views['datetime'].dt.month
views['day'] = views['datetime'].dt.day
views['hour'] = views['datetime'].dt.hour
views['minute'] = views['datetime'].dt.minute
views['second'] = views['datetime'].dt.second

views

,datetime,user,year,month,day,hour,minute,second
0,2020-04-17 12:01:08.463179,artem,2020,4,17,12,1,8
1,2020-04-17 12:01:23.743946,artem,2020,4,17,12,1,23
2,2020-04-17 12:27:30.646665,artem,2020,4,17,12,27,30
3,2020-04-17 12:35:44.884757,artem,2020,4,17,12,35,44
4,2020-04-17 12:35:52.735016,artem,2020,4,17,12,35,52
...,...,...,...,...,...,...,...,...
1071,2020-05-21 18:45:20.441142,valentina,2020,5,21,18,45,20
1072,2020-05-21 23:03:06.457819,maxim,2020,5,21,23,3,6
1073,2020-05-21 23:23:49.995349,pavel,2020,5,21,23,23,49
1074,2020-05-21 23:49:22.386789,artem,2020,5,21,23,49,22
1075,2020-05-22 10:36:14.662600,artem,2020,5,22,10,36,14

In [ ]:
# 2. Создайте новый столбец daytime.

# Присвойте значение времени суток, если час попадает в определённый интервал. Например, присвойте значение «после полудня», если час больше 11, но меньше или равен 17.
# 0–3:59 = ночь, 4–6:59 = раннее утро, 7–10:59 = утро, 11–16:59 = день, 17–19:59 = ранний вечер, 20–23:59 = вечер.
# Используйте метод cutдля решения этой подзадачи.
# Назначьте столбец userв качестве индекса.
label = ['night', 'early morning', 'morning', 'afternoon', 'early evening', 'evening']

bin = [0, 4, 7, 11, 17, 20, 24]
views['daytime'] = pd.cut(views.hour, bins = bin , labels = label, right=False)
views

,datetime,user,year,month,day,hour,minute,second,daytime
0,2020-04-17 12:01:08.463179,artem,2020,4,17,12,1,8,afternoon
1,2020-04-17 12:01:23.743946,artem,2020,4,17,12,1,23,afternoon
2,2020-04-17 12:27:30.646665,artem,2020,4,17,12,27,30,afternoon
3,2020-04-17 12:35:44.884757,artem,2020,4,17,12,35,44,afternoon
4,2020-04-17 12:35:52.735016,artem,2020,4,17,12,35,52,afternoon
...,...,...,...,...,...,...,...,...,...
1071,2020-05-21 18:45:20.441142,valentina,2020,5,21,18,45,20,early evening
1072,2020-05-21 23:03:06.457819,maxim,2020,5,21,23,3,6,evening
1073,2020-05-21 23:23:49.995349,pavel,2020,5,21,23,23,49,evening
1074,2020-05-21 23:49:22.386789,artem,2020,5,21,23,49,22,evening
1075,2020-05-22 10:36:14.662600,artem,2020,5,22,10,36,14,morning

In [24]:
#Назначьте столбец userв качестве индекса.
views = views.set_index('user')
views

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
artem,2020-04-17 12:01:08.463179,2020,4,17,12,1,8,afternoon
artem,2020-04-17 12:01:23.743946,2020,4,17,12,1,23,afternoon
artem,2020-04-17 12:27:30.646665,2020,4,17,12,27,30,afternoon
artem,2020-04-17 12:35:44.884757,2020,4,17,12,35,44,afternoon
artem,2020-04-17 12:35:52.735016,2020,4,17,12,35,52,afternoon
...,...,...,...,...,...,...,...,...
valentina,2020-05-21 18:45:20.441142,2020,5,21,18,45,20,early evening
maxim,2020-05-21 23:03:06.457819,2020,5,21,23,3,6,evening
pavel,2020-05-21 23:23:49.995349,2020,5,21,23,23,49,evening
artem,2020-05-21 23:49:22.386789,2020,5,21,23,49,22,evening
artem,2020-05-22 10:36:14.662600,2020,5,22,10,36,14,morning

In [25]:
#3. Рассчитайте количество элементов в вашем фрейме данных.

# Используйте метод count().
# Рассчитайте количество элементов в каждой категории времени суток, используя данный value_counts()метод.

views.count()

datetime    1076
year        1076
month       1076
day         1076
hour        1076
minute      1076
second      1076
daytime     1076
dtype: int64

In [26]:
views.value_counts('daytime')

daytime
evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: count, dtype: int64

In [27]:
#Сортируйте значения в таблице данных по часам,
# минутам и секундам в порядке возрастания одновременно, а не по одному.

sort_e = views.sort_values(by=['hour', 'minute', 'second'])

sort_e

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
valentina,2020-05-15 00:00:13.222265,2020,5,15,0,0,13,night
valentina,2020-05-15 00:01:05.153738,2020,5,15,0,1,5,night
pavel,2020-05-12 00:01:27.764025,2020,5,12,0,1,27,night
pavel,2020-05-12 00:01:38.444917,2020,5,12,0,1,38,night
pavel,2020-05-12 00:01:55.395042,2020,5,12,0,1,55,night
...,...,...,...,...,...,...,...,...
artem,2020-05-21 23:49:22.386789,2020,5,21,23,49,22,evening
anatoliy,2020-05-09 23:53:55.599821,2020,5,9,23,53,55,evening
pavel,2020-05-09 23:54:54.260791,2020,5,9,23,54,54,evening
valentina,2020-05-14 23:58:56.754866,2020,5,14,23,58,56,evening
alexander,2020-05-14 23:59:38.758438,2020,5,14,23,59,38,evening

In [28]:
# 5. Рассчитайте минимум и максимум для часов, а также режим для дневных категорий.
# Рассчитайте максимальный час для строк, где время суток — ночь.
# Рассчитайте минимальный час для строк, где время суток — утро.
# Кроме того, выясните, кто посещал страницу в эти часы, и приведите один пример.
# Рассчитайте моду для часа и времени суток.

print(views[views.daytime == 'night']['hour'].max())
print(views[views.daytime == 'morning']['hour'].min())

views[views['hour'] == views[views.daytime == 'night']['hour'].max()]

3
8

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
konstantin,2020-04-19 03:23:35.471598,2020,4,19,3,23,35,night
konstantin,2020-04-19 03:23:55.473926,2020,4,19,3,23,55,night
konstantin,2020-04-19 03:33:07.757714,2020,4,19,3,33,7,night

In [29]:
views[(views['hour'] == views[views.daytime == 'morning']['hour'].min())]

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
alexander,2020-05-15 08:16:03.918402,2020,5,15,8,16,3,morning
alexander,2020-05-15 08:35:01.471463,2020,5,15,8,35,1,morning

In [30]:
views['hour'].mode()

0    22
Name: hour, dtype: int32

In [31]:
views['daytime'].mode()

0    evening
Name: daytime, dtype: category
Categories (6, object): ['night' < 'early morning' < 'morning' < 'afternoon' < 'early evening' < 'evening']

In [32]:
# Показывать три самых ранних и три самых поздних часа дня и соответствующие им
# имена пользователей с помощью nsmallest()и nlargest().
views[views['daytime'] == 'afternoon'].nsmallest(3, 'hour')

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
artem,2020-04-18 11:02:42.796521,2020,4,18,11,2,42,afternoon
artem,2020-04-19 11:15:55.042662,2020,4,19,11,15,55,afternoon
artem,2020-04-21 11:02:44.545611,2020,4,21,11,2,44,afternoon

In [33]:

views[views['daytime'] == 'morning'].nlargest(3, ['hour'])

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
konstantin,2020-04-18 10:53:52.623447,2020,4,18,10,53,52,morning
maxim,2020-04-18 10:56:55.833899,2020,4,18,10,56,55,morning
konstantin,2020-04-18 10:57:37.331258,2020,4,18,10,57,37,morning

In [34]:
views.describe()

,datetime,year,month,day,hour,minute,second
count,1076,1076.0,1076.000000,1076.000000,1076.000000,1076.000000,1076.000000
mean,2020-05-10 09:00:41.211420672,2020.0,4.870818,13.552974,16.249071,29.629182,29.500929
min,2020-04-17 12:01:08.463179,2020.0,4.000000,1.000000,0.000000,0.000000,0.000000
25%,2020-05-10 01:13:49.857472,2020.0,5.000000,11.000000,13.000000,14.000000,14.000000
50%,2020-05-11 22:48:35.302552832,2020.0,5.000000,13.000000,19.000000,29.000000,30.000000
75%,2020-05-14 14:44:34.749530624,2020.0,5.000000,15.000000,22.000000,46.000000,45.000000
max,2020-05-22 10:36:14.662600,2020.0,5.000000,30.000000,23.000000,59.000000,59.000000
std,NaN,0.0,0.335557,4.906567,6.955490,17.689388,17.405506

In [35]:
views.describe()

,datetime,year,month,day,hour,minute,second
count,1076,1076.0,1076.000000,1076.000000,1076.000000,1076.000000,1076.000000
mean,2020-05-10 09:00:41.211420672,2020.0,4.870818,13.552974,16.249071,29.629182,29.500929
min,2020-04-17 12:01:08.463179,2020.0,4.000000,1.000000,0.000000,0.000000,0.000000
25%,2020-05-10 01:13:49.857472,2020.0,5.000000,11.000000,13.000000,14.000000,14.000000
50%,2020-05-11 22:48:35.302552832,2020.0,5.000000,13.000000,19.000000,29.000000,30.000000
75%,2020-05-14 14:44:34.749530624,2020.0,5.000000,15.000000,22.000000,46.000000,45.000000
max,2020-05-22 10:36:14.662600,2020.0,5.000000,30.000000,23.000000,59.000000,59.000000
std,NaN,0.0,0.335557,4.906567,6.955490,17.689388,17.405506

In [36]:
# Используйте этот describe()метод для получения основных статистических данных по столбцам.

# Чтобы определить наиболее популярный интервал посещения, рассчитайте межквартильный размах для часа, извлекая значения из результата метода describe()и сохраняя их в переменной iqr.
stats = views['hour'].describe()
q3_q1 = stats['75%'] - stats['25%']
q3_q1

np.float64(9.0)