In [2]:
import pandas as pd

In [3]:
# Скачайте и прочтите CSV-файл, создав IDстолбец индекса.
auto = pd.read_csv('../data/auto.csv', index_col='ID')

In [4]:
#2. Подсчитайте количество наблюдений, используя этот метод count().

auto.count()

CarNumber       931
Make_n_model    931
Refund          914
Fines           869
History          82
dtype: int64

In [5]:
# Удалите дубликаты, учитывая только следующие столбцы: CarNumber, Make_n_Model, и Fines.

# Из двух одинаковых наблюдений выберите последнее.
# Ещё раз проверьте количество наблюдений.
auto = auto.drop_duplicates(subset=['CarNumber', 'Make_n_model', 'Fines'], keep='last')
auto.count()

CarNumber       725
Make_n_model    725
Refund          713
Fines           665
History          65
dtype: int64

3. Работа с пропущенными значениями.

Проверьте, сколько значений отсутствует в каждом столбце.
Удалите все столбцы, содержащие более 500 пропущенных значений, используя аргумент thresh. Проверьте, сколько пропущенных значений содержится в каждом столбце.
Замените все пропущенные значения в Refundстолбце предыдущим значением в этом столбце для данной ячейки. Используйте метод аргументов и проверьте количество пропущенных значений в каждом столбце.
Замените все пропущенные значения в Finesстолбце средним значением этого столбца (исключая значения NA/NULL при вычислении среднего). Проверьте количество пропущенных значений в каждом столбце.

In [6]:
missint_count=auto.isnull().sum()
print(missint_count)

CarNumber         0
Make_n_model      0
Refund           12
Fines            60
History         660
dtype: int64

In [7]:
auto = auto.dropna(thresh=500, axis=1)
auto.isnull().sum()

CarNumber        0
Make_n_model     0
Refund          12
Fines           60
dtype: int64

In [8]:
# Заменяем пропущенные значения в столбце Refund предыдущим значением
auto['Refund'] = auto['Refund'].fillna(method='ffill')
auto.isnull().sum()

/var/folders/_d/q8_c5ntn1zsdjh_6zk89_ch40000gn/T/ipykernel_4212/1992165486.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  auto['Refund'] = auto['Refund'].fillna(method='ffill')

CarNumber        0
Make_n_model     0
Refund           0
Fines           60
dtype: int64

In [9]:
#Заменим все пропущенные значения в столбце Fines средним значением этого столбца
auto['Fines'].fillna(auto['Fines'].mean(), inplace=True)
auto.isna().sum()

/var/folders/_d/q8_c5ntn1zsdjh_6zk89_ch40000gn/T/ipykernel_4212/1870748553.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  auto['Fines'].fillna(auto['Fines'].mean(), inplace=True)

CarNumber       0
Make_n_model    0
Refund          0
Fines           0
dtype: int64

In [10]:
# Разделите и проанализируйте марку и модель.

# Используйте метод apply для разделения и извлечения значений в новые столбцы, Makeа также Model.
# Удалить столбец Make_n_Model.
# Сохраните фрейм данных в auto.jsonJSON-файл в указанном ниже формате:

auto

        CarNumber    Make_n_model  Refund         Fines
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.000000
1     E432XX77RUS    Toyota Camry     1.0   6500.000000
2     7184TT36RUS      Ford Focus     1.0   2100.000000
3    X582HE161RUS      Ford Focus     2.0   2000.000000
5    92918M178RUS      Ford Focus     1.0   5700.000000
..            ...             ...     ...           ...
926  Y163O8161RUS      Ford Focus     2.0   1600.000000
927  M0309X197RUS      Ford Focus     1.0  22300.000000
928  O673E8197RUS      Ford Focus     2.0    600.000000
929  8610T8154RUS      Ford Focus     1.0   2000.000000
930  H419XE197RUS  Toyota Corolla     2.0   8594.586466

[725 rows x 4 columns]

In [11]:
auto['Make'] = auto['Make_n_model'].apply(lambda x: x.split()[0])
auto['Model'] = auto['Make_n_model'].apply(lambda x: x.split()[1] if len(x.split()) == 2 else None)
auto.drop('Make_n_model', inplace=True, axis=1)

auto

        CarNumber  Refund         Fines    Make    Model
ID
0    Y163O8161RUS     2.0   3200.000000    Ford    Focus
1     E432XX77RUS     1.0   6500.000000  Toyota    Camry
2     7184TT36RUS     1.0   2100.000000    Ford    Focus
3    X582HE161RUS     2.0   2000.000000    Ford    Focus
5    92918M178RUS     1.0   5700.000000    Ford    Focus
..            ...     ...           ...     ...      ...
926  Y163O8161RUS     2.0   1600.000000    Ford    Focus
927  M0309X197RUS     1.0  22300.000000    Ford    Focus
928  O673E8197RUS     2.0    600.000000    Ford    Focus
929  8610T8154RUS     1.0   2000.000000    Ford    Focus
930  H419XE197RUS     2.0   8594.586466  Toyota  Corolla

[725 rows x 5 columns]

In [12]:
auto.to_json('auto.json', orient='records', indent=2)