In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(
    '../data/feed-views.log',
    skiprows=[2, 3],
    skipfooter=2,
    names=['datetime', 'user'],
    index_col='datetime',
    engine= 'python',
    sep= '\t'
)
#пропускает 2 и 3 строки (считая с 0), пропускает последние 2 строки,
#задаёт имена столбцов,
#делает datetime индексом.

df

                                 user
datetime
2020-04-17 12:01:08.463179      artem
2020-04-17 12:01:23.743946      artem
2020-04-17 12:35:52.735016      artem
2020-04-17 12:36:21.401412     oksana
2020-04-17 12:36:22.023355     oksana
...                               ...
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

[1072 rows x 1 columns]

In [6]:
#Переименовать datetime date_time.
df.rename(columns={'datetime':'date_time'})
df.head()

                              user
datetime
2020-04-17 12:01:08.463179   artem
2020-04-17 12:01:23.743946   artem
2020-04-17 12:35:52.735016   artem
2020-04-17 12:36:21.401412  oksana
2020-04-17 12:36:22.023355  oksana

In [7]:
# to_csv:
# Использовать ’;’как разделитель.
# Сохраните его в файле с именем feed-views-semicolon.log.

df.to_csv('feed-views-semicolon.log', sep=';')